const types = {
    SET_CUSTOMER: '@shop/SET_CUSTOMER',
    REQUEST_HEALTH_SHOPS: '@shop/REQUEST_HEALTH_SHOPS',
    SET_HEALTSHOP: '@shop/SET_HEALTSHOP',
    SET_HEALTH_MAP_SELECTED: '@shop/SET_HEALTH_MAP_SELECTED',
    SET_MAP_CENTER: '@shop/SET_MAP_CENTER',
    RESQUEST_HEALTH_SHOP: '@shop/RESQUEST_HEALTH_SHOP',
    SET_HEALTHSTORE: '@shop/SET_HEALTHSTORE',
    TOGGLE_CART_PRODUCT: '@shop/TOGGLE_CART_PRODUCT',
    SET_TRANSACTION: '@shop/SET_TRANSACTION',
    // MAKE_PURCHASE: '@shop/MAKE_PURCHASE',
}

export default types;